# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "openai"
  model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" # or gpt-3.5-turbo
  base_url: "https://api.siliconflow.cn/v1" # or forward url / other llm url
  api_key: "sk-fyzjswudttsldladbtjreqdwcczoywlddgwsgtjjkctvabyd"
